### ISSUE TITLE
有些App使用DexKit - System.loadLibrary("dexkit")时会出现异常

### ISSUE THREAD

**Issue by BryenZ** [LuckyPray/DexKit#14]
不太清楚为什么会报错 java.lang.UnsatisfiedLinkError: LspModuleClassLoader , 作者大大可以提供一些帮助吗? 报错指向的是System.loadLibrary("dexkit") .
有些App则是正常的不报错

**Comment by teble** [comment]
提供一下apk文件

**Comment by teble** [comment]
~~哦，我看错了，我以为解析出错了~~，加载依赖库报错的话又更详细的信息吗

**Comment by xsk666** [comment]
minSdkVersion至少需要23捏  ~血淋淋的教训~

**Comment by teble** [comment]
> minSdkVersion至少需要23捏 ~血淋淋的教训~

但是他给的报错信息有个奇怪的LspModuleClassLoader，就很奇怪，我记得低于23好像是别的信息

**Comment by teble** [comment]
> `好像是因为我设备是64位的, 应用是32位的,所以就会报错`

我想起来了，以前写模块的时候确实碰过这种情况，System. loadLibrary加载的so与虚拟机不一致的情况。后面是自己手动写了个解压来解决的。
- 反射调用 `dalvik.system.VMRuntime.is64Bit()` 来判断当前运行环境 (VMRuntime内部存在一个单例)
- 调用 `moduleClassLoader.getResourceAsStream("lib/{abi}/libdexkit.so")` 将so解压至任意目录（注意判断是否存在更新）
- `System.load(soFile.absolutePath)`
