### ISSUE TITLE
有搜索某些类的field的方法吗？

### ISSUE THREAD

**Issue by javaeryang** [LuckyPray/DexKit#16]
类名和方法名都比较好定位，唯一就是差field不太好定位。可否考虑一下增加辅助定位field的方法。

**Comment by teble** [comment]
可以在目前findClass的基础上简单的支持一下field_type以及field_name，不知是否够用？
因为在当初的设计中下意识认为field是被混淆的状态了

**Comment by teble** [comment]
目前正在进行2.0版本的重写，你说的这些用法会在2.0中的新API中得到支持，但是对于1.x版本的DexKit因为底层设计原因无法在基础上进行实现

**Comment by javaeryang** [comment]
好的，这样的话就比较好用一些，全面一点。

**Comment by teble** [comment]
重写已完成，但是未完全测试，这几天应该会发2.0测试版本，欢迎到时试用

**Comment by teble** [comment]
2.0.0-alpha 已发布，欢迎测试，如有疑问请开新 issue
