### ISSUE TITLE
编译失败，请问大佬这个错误如何解决

### ISSUE THREAD

**Issue by javaeryang** [LuckyPray/DexKit#18]
userNameXXX@localhost DexKit % ./gradlew clean :main:run             

> Configure project :dexkit-android
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :dexkit-android:externalNativeBuildCleanDebug
Clean dexkit-x86, dexkit_static-x86

> Task :dexkit:cmakemain_mac-aarch64
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found JNI: NotNeeded  
-- Disable dexkit log
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/userNameXXX/Documents/AndroidProjects/DexKit/dexkit/build/cmake/main/mac-aarch64

> Task :dexkit:main_mac-aarch64_runGeneratorUnix_Makefiles
[  4%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/bytecode_encoder.cc.o
[  8%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/code_ir.cc.o
[ 12%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/common.cc.o
[ 16%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/control_flow_graph.cc.o
[ 20%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/debuginfo_encoder.cc.o
[ 24%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_bytecode.cc.o
[ 28%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_format.cc.o
[ 32%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_ir.cc.o
[ 36%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_ir_builder.cc.o
[ 40%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_utf8.cc.o
[ 44%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/instrumentation.cc.o
[ 48%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/reader.cc.o
[ 52%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/tryblocks_encoder.cc.o
[ 56%] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/writer.cc.o
[ 60%] Building CXX object Core/CMakeFiles/dexkit_static.dir/dexkit/beans.cpp.o
[ 64%] Building CXX object Core/CMakeFiles/dexkit_static.dir/dexkit/common.cpp.o
[ 68%] Building CXX object Core/CMakeFiles/dexkit_static.dir/dexkit/dex_item.cpp.o
/Users/userNameXXX/Documents/AndroidProjects/DexKit/Core/dexkit/dex_item.cpp:589:32: error: no member named 'all_of' in namespace 'std::ranges'
    auto all_of = std::ranges::all_of(types, [this](std::string_view type_name) {
                  ~~~~~~~~~~~~~^
1 error generated.
make[2]: *** [Core/CMakeFiles/dexkit_static.dir/dexkit/dex_item.cpp.o] Error 1
make[1]: *** [Core/CMakeFiles/dexkit_static.dir/all] Error 2
make: *** [all] Error 2

> Task :dexkit:main_mac-aarch64_runGeneratorUnix_Makefiles FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexkit:main_mac-aarch64_runGeneratorUnix_Makefiles'.
> Process 'command 'make'' finished with non-zero exit value 2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
10 actionable tasks: 7 executed, 3 up-to-date
userNameXXX@localhost DexKit % ./gradlew clean :main:run

> Configure project :dexkit-android
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :dexkit-android:externalNativeBuildCleanDebug
Clean dexkit-x86, dexkit_static-x86

> Task :dexkit:cmakemain_mac-aarch64
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found JNI: NotNeeded  
-- Disable dexkit log
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/userNameXXX/Documents/AndroidProjects/DexKit/dexkit/build/cmake/main/mac-aarch64

> Task :dexkit:main_mac-aarch64_runGeneratorNinja
[1/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/common.cc.o
[2/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_format.cc.o
[3/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_bytecode.cc.o
[4/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_utf8.cc.o
[5/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/control_flow_graph.cc.o
[6/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/debuginfo_encoder.cc.o
[7/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_ir.cc.o
[8/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/dexkit/common.cpp.o
[9/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/dex_ir_builder.cc.o
[10/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/bytecode_encoder.cc.o
[11/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/tryblocks_encoder.cc.o
[12/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/instrumentation.cc.o
[13/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/code_ir.cc.o
[14/25] Building CXX object CMakeFiles/dexkit.dir/native-bridge.cpp.o
[15/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/dexkit/beans.cpp.o
[16/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/writer.cc.o
[17/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/third_party/slicer/reader.cc.o
[18/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/dexkit/dex_item_find.cpp.o
[19/25] Building CXX object Core/CMakeFiles/dexkit_static.dir/dexkit/dex_item.cpp.o
FAILED: Core/CMakeFiles/dexkit_static.dir/dexkit/dex_item.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/Users/userNameXXX/Documents/AndroidProjects/DexKit/Core/dexkit/include -I/Users/userNameXXX/Documents/AndroidProjects/DexKit/Core/third_party/slicer/export -I/Users/userNameXXX/Documents/AndroidProjects/DexKit/Core/third_party/thread_helper -I/Users/userNameXXX/Documents/AndroidProjects/DexKit/Core/third_party/aho_corasick_trie -I/Users/userNameXXX/Documents/AndroidProjects/DexKit/Core/third_party/parallel_hashmap -I/Users/userNameXXX/Documents/AndroidProjects/DexKit/Core/third_party/flatbuffers/include -Wno-empty-body -Wno-unused-private-field     -Wno-unused-value -Wno-unused-variable -Wno-unused-function -pthread -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++2a -MD -MT Core/CMakeFiles/dexkit_static.dir/dexkit/dex_item.cpp.o -MF Core/CMakeFiles/dexkit_static.dir/dexkit/dex_item.cpp.o.d -o Core/CMakeFiles/dexkit_static.dir/dexkit/dex_item.cpp.o -c /Users/userNameXXX/Documents/AndroidProjects/DexKit/Core/dexkit/dex_item.cpp
/Users/userNameXXX/Documents/AndroidProjects/DexKit/Core/dexkit/dex_item.cpp:589:32: error: no member named 'all_of' in namespace 'std::ranges'
    auto all_of = std::ranges::all_of(types, [this](std::string_view type_name) {
                  ~~~~~~~~~~~~~^
1 error generated.

**Comment by javaeryang** [comment]
alpha6没问题了

**Comment by teble** [comment]
> alpha6没问题了

libcxx精简掉了部分stdlib函数，所以导致ndk编译错误，昨晚上已经改了
