### ISSUE TITLE
新版的查找方法问题反馈

### ISSUE THREAD

**Issue by javaeryang** [LuckyPray/DexKit#20]
查找代码
<img width="628" alt="image" src="https://github.com/LuckyPray/DexKit/assets/27242250/e32cde44-c151-4daa-81d8-4a1611b1a3d1">
输出
<img width="816" alt="image" src="https://github.com/LuckyPray/DexKit/assets/27242250/f88e7ac5-4163-4e76-af0f-bf39970d9751">
输出非常多结果，且结果是错误的，okhttp3的类都搜索出来了。
我之前用alpha-6好像没这个问题。
代码我拉的主分支最新代码。
是我使用上有问题了吗？

**Comment by teble** [comment]
是哪个app的哪个版本，我看一下

**Comment by teble** [comment]
代码更新后有clean，重新build动态库吗

**Comment by javaeryang** [comment]
> 代码更新后有clean，重新build动态库吗

没有，我clean试一下。

**Comment by javaeryang** [comment]
> 代码更新后有clean，重新build动态库吗

没有，我clean试一下。

**Comment by javaeryang** [comment]
已解决，clean后重新编译运行，正常了。感谢大佬。

**Comment by teble** [comment]
近期有对底层序列化的数据进行结构更改，所以反序列化的时候，如果与动态库中的结构对不上可能会构建出错误的查询

**Comment by javaeryang** [comment]
> 近期有对底层序列化的数据进行结构更改，所以反序列化的时候，如果与动态库中的结构对不上可能会构建出错误的查询

下次会注意了，每次拉取，都clean一下，应该就好了。
