### ISSUE TITLE
关于2.0的对于方法参数推测功能的猜想

### ISSUE THREAD

**Issue by GangJust** [LuckyPray/DexKit#21]
不知道2.0有么有类似于这样的操作

例如在某个类中有这样一个方法：

```kotlin
private void abc(View p1, KWB p2, int p3){
	//some logic..
}
````

其中参数2是被混淆的类型。

```kotlin
...
methods {
    // 添加对于方法的匹配器
    add {
        modifiers = Modifier.PRIVATE
        paramTypes = listOf("android.view.View","java.lang.Object","I") //模糊匹配第二个参数
    }
}
...
```

当然如果这样进行模糊匹配的话，搜寻耗时肯定会大大增加。
（小声，没试过，不知道有没有这种逻辑，没有或没打算也没啥，哈哈哈，2.0的新搜索已经很细了）

**Comment by teble** [comment]
注意paramTypes的类型是List<ClassMatcher?>，设置为null即可匹配任意类型

**Comment by GangJust** [comment]
> 注意paramTypes的类型是List<ClassMatcher?>，设置为null即可匹配任意类型

好的，多谢，哈哈哈
