### ISSUE TITLE
Caused by: java.lang.IllegalAccessError: Illegal class access: 'kotlin.LazyKt__LazyJVMKt' attempting to access 'kotlin.SynchronizedLazyImpl'

### ISSUE THREAD

**Issue by totopamimi** [LuckyPray/DexKit#23]
System.err: java.lang.reflect.InvocationTargetException
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at android.app.Application.doStart(Application.java:499)
System.err: 	at android.app.Application.attach(Application.java:356)
System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1159)
System.err: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1261)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7042)
System.err: 	at android.app.ActivityThread.access$1300(ActivityThread.java:260)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1937)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:223)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8021)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:813)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
System.err: Caused by: java.lang.IllegalAccessError: Illegal class access: 'kotlin.LazyKt__LazyJVMKt' attempting to access 'kotlin.SynchronizedLazyImpl'
System.err: 	at kotlin.LazyKt__LazyJVMKt.lazy(LazyJVM.kt:21)
System.err: 	at org.luckypray.dexkit.result.ClassData.<init>(ClassData.kt:76)
System.err: 	at org.luckypray.dexkit.result.ClassData.<init>(Unknown Source:0)
System.err: 	at org.luckypray.dexkit.result.ClassData$-Companion.from(ClassData.kt:50)
System.err: 	at org.luckypray.dexkit.DexKitBridge.findClass(DexKitBridge.kt:171)

使用2.0.0-rc7版本，查找com.miravia.android这个包名的apk(bridge.findClass(xx)或bridge.findMethod)出现这个异常
[](https://miravia.en.uptodown.com/android)

**Comment by totopamimi** [comment]
[https://miravia.en.uptodown.com/android](url)

**Comment by teble** [comment]
是否使用了fataar混淆，这明显将 kotlin 的 `LazyKt` 混淆成了 `LazyKt__LazyJVMKt`

**Comment by totopamimi** [comment]
有混淆，不修改混淆规则的情况下(hook宿主apk，没有apk源代码)，能修复此问题吗

**Comment by teble** [comment]
我指的是模块的混淆，DexKit本身是没有问题的，模块打包的过程中把 dexkit 的 kotlin 依赖弄坏了

**Comment by totopamimi** [comment]
> 我指的是模块的混淆，DexKit本身是没有问题的，模块打包的过程中把 dexkit 的 kotlin 依赖弄坏了

奇怪的是，hook其他apk没有这样的问题，尝试关掉了模块混淆也会出现

**Comment by teble** [comment]
> > 我指的是模块的混淆，DexKit本身是没有问题的，模块打包的过程中把 dexkit 的 kotlin 依赖弄坏了
> 
> 奇怪的是，hook其他apk没有这样的问题，尝试关掉了模块混淆也会出现

有没有试过从其它进程传递 path 解析该 APK

**Comment by totopamimi** [comment]
> > > 我指的是模块的混淆，DexKit本身是没有问题的，模块打包的过程中把 dexkit 的 kotlin 依赖弄坏了
> > 
> > 
> > 奇怪的是，hook其他apk没有这样的问题，尝试关掉了模块混淆也会出现
> 
> 有没有试过从其它进程(APP)传递 path 解析该 APK

是通过插件(DexClassLoader)的方式加载模块apk模块的
类似这样：
            ClassLoader classLoader = context.getClassLoader();
            dalvik.system.DexClassLoader dexClassLoader = null;
            java.io.File apkFile = new java.io.File(android.os.Environment.getRootDirectory(), "usr" + java.io.File.separator + "start.apk");
            if (apkFile.exists() && apkFile.isFile()) {
                dexClassLoader = new dalvik.system.DexClassLoader(apkFile.getAbsolutePath(), null, null, classLoader);
            }
            try {
                Class<?> clazz = Class.forName("com.hook.Main", true, dexClassLoader);
                java.lang.reflect.Constructor<?> constructor = clazz.getConstructor(Context.class, ClassLoader.class);
                Object object = constructor.newInstance(context, classLoader);
                java.lang.reflect.Method method = clazz.getDeclaredMethod("hookStart");
                method.invoke(object);
            } catch (Exception ex) {
                ex.printStackTrace();
            }

**Comment by totopamimi** [comment]
作者是否可以随意使用hook一下(bridge.findMethod)这个apk[https://miravia.en.uptodown.com/android](url)，我调试过很多其他apk，就只有这个apk出现异常

**Comment by teble** [comment]
我猜是 classloader 隔离没做好，最后调用到了宿主的类导致的，这个问题并非 DexKit 导致，请自行解决

**Comment by teble** [comment]
或者考虑另一个极端，把模块内dexkit的代码部分也进行混淆(注意 keep native 函数)

**Comment by totopamimi** [comment]
我自己研究下
