### ISSUE TITLE
求助 权限问题

### ISSUE THREAD

**Issue by HChenX** [LuckyPray/DexKit#24]
在执行dexkit的时候发生如下报错：
java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/app/~~XJDf3lkJxeo86nnpZPIaEw==/Com.HChen.Hook-x7LVELe3pOsPXPq7ZvcVAQ==/base.apk!/lib/arm64-v8a/libdexkit.so" segment 1: Permission denied
对象是Athena App

**Comment by HChenX** [comment]
/data/app/~~XJDf3lkJxeo86nnpZPIaEw==/Com.HChen.Hook-x7LVELe3pOsPXPq7ZvcVAQ==/base.apk
权限rw r  r
用户/组system

**Comment by teble** [comment]
minsdk多少，设备是8.0？

**Comment by HChenX** [comment]
> minsdk多少，设备是8.0？

minsdk 32 
设备 oppo find x6pro 安卓13

**Comment by teble** [comment]
尝试解压到一个指定目录再加载呢？

**Comment by HChenX** [comment]
> 为什么要解压到/data/lib？

那应该放在什么目录内

**Comment by teble** [comment]
宿主的私有目录

**Comment by HChenX** [comment]
> 宿主的私有目录

也就是/data/app/~~XJDf3lkJxeo86nnpZPIaEw==/Com.HChen.Hook-x7LVELe3pOsPXPq7ZvcVAQ==/lib里面吗，还有其他地方需要更改吗？还是使用System.loadLibrary("dexkit")？

**Comment by teble** [comment]
正常情况使用 `System.loadLibrary("dexkit")` 就行，但是你不是会出错？
宿主APP的私有目录，而不是你插件的私有目录，例如: `/data/usr/0/package/files/xxlib/libdexkit.so`

**Comment by HChenX** [comment]
> 正常情况使用 `System.loadLibrary("dexkit")` 就行，但是你不是会出错？ 宿主APP的私有目录，而不是你插件的私有目录，例如: `/data/usr/0/package/files/xxlib/libdexkit.so`

我自己研究了一下，放到/data/usr/0/package/files/libdexkit.so反而提示segment 1: Permission denied，但是关闭selinux就正常了

**Comment by teble** [comment]
https://github.com/android/ndk/issues/979

https://issuetracker.google.com/issues/127691101

**Comment by HChenX** [comment]
> [android/ndk#979](https://github.com/android/ndk/issues/979)
> 
> https://issuetracker.google.com/issues/127691101

按照上面的方法测试了一下，还是不行。
但是我有看了一会发现，只有重启第一次加载模块查找Athena hook点时会报错segment 1: Permission denied，如果之后我手动结束Athena 等他自启动触发dexkit他又正常查找了。
模块开机第一次运行
[HChenHook][AthenaApp]: E: un error:java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/app/~~U5FHOJxiGLJwnxlw2l9smA==/Com.HChen.Hook-6pzDNsKILGdqVf6uTXZpcw==/base.apk!/lib/arm64-v8a/libdexkit.so" segment 1: Permission denied
Athena 启动触发
[HChenHook][AthenaApp]: I: class: j4.f method: c

**Comment by teble** [comment]
设备系统问题，/data/app 下的 apk 是允许通过 mmap 加载 so 的，之前提到的几个 issue 以及 google 给出的方案是压缩 apk 内的 so 文件，从而强行使设备解压 apk 内的 so 文件至 lib 目录，但是很可惜你是模块，宿主内是无法直接访问模块的 lib 目录内的文件。

如果出现异常请尝试在宿主内使用代码解压 so 到 mount 状态为非 noexec 的目录（注意不是手动 root 解压，文件是有所属权限的）
