### ISSUE TITLE
opNames匹配不到

### ISSUE THREAD

**Issue by Girpex** [LuckyPray/DexKit#25]
opNames(Arrays.asList("new-instance", "invoke-direct", "invoke-virtual", "invoke-virtual", "move-result-object", "if-eqz", "return-object", "new-instance", "invoke-direct", "throw"))

**Comment by teble** [comment]
反编译的smali跟dex一个都没提供，这是让我算命吗

**Comment by Dev4Mod** [comment]
The opnames are not working, I have done several tests but it always returns that no method was found

**Comment by teble** [comment]
> The opnames are not working, I have done several tests but it always returns that no method was found

Can you provide a reproducible example? dex/apk and query examples

**Comment by Dev4Mod** [comment]
APK: https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/whatsapp-2-24-7-79-release/
hooked class: X.1ii
hooked method: A0b(I)V
disassembly: 
```
0000: iget v0, v1, LX/1ii;->A17:I
0002: or-int/2addr v2, v0
0003: iput v2, v1, LX/1ii;->A17:I
0005: return-void
```

code used:
 dexkitInstance.findMethod(new FindMethod().matcher(new MethodMatcher().opCodes(
            new OpCodesMatcher().opNames(List.of("iget","or-int/2addr","iput","return-void"))
        )));

**Comment by teble** [comment]
2.0.1 Fixed
