### ISSUE TITLE
Package匹配问题

### ISSUE THREAD

**Issue by CLOUDERHEM** [LuckyPray/DexKit#28]
偶然发现, 执行类似如下搜索的时候, 设置`search_package = "com.ab"`, 然后比如`com.abc.A`也会被匹配有效

按理来说这两个应该属于不同的`package`, 所以想问问大佬这是bug还说是feat就是这样的匹配模式?

> 应该是这里的代码: [package_trie.h](https://github.com/LuckyPray/DexKit/blob/417fdeb0a4efba6f28c3cfb71370c1b5230c6a59/Core/dexkit/include/package_trie.h#L63C9-L82C21)

**Comment by teble** [comment]
目前只用了个前缀树匹配，确定某个包名改成 com.ab.

**Comment by teble** [comment]
这个其实当时拿捏不准要不要当成一个确切的包名使用，后面还是改一下比较好，暂时就尾部加 `.` 来解决。
现在这样仔细想想其实还是有问题的，比如有一个 `com.abdf` 的类也会被当成匹配的结果

**Comment by teble** [comment]
2.0.2 已更正此问题
