### ISSUE TITLE
[Feat] 支持查找已优化的 DEX 文件

### ISSUE THREAD

**Issue by EatHatsuneShallots** [LuckyPray/DexKit#30]
https://github.com/LuckyPray/DexKit/issues/29#issuecomment-2211903339

**Comment by teble** [comment]
@EatHatsuneShallots 目前不会考虑提供odex支持

**Comment by EatHatsuneShallots** [comment]
某些应用含有混淆，（可能）只能动态获取已加载的 dex 文件，甚至可能会删除 dex 文件，只保留已优化的文件

**Comment by teble** [comment]
@EatHatsuneShallots apk不应该存在dex被删除的情况，直接使用sourceDir的路径解析即可

**Comment by EatHatsuneShallots** [comment]
> @EatHatsuneShallots apk不应该存在dex被删除的情况

内置的 apk 和核心破解应该可以，并且 apk 可能会加固，导致获取不到类列表

**Comment by teble** [comment]
@EatHatsuneShallots 系统不会对apk进行改动，即使有核心破解的存在，你所描述的并非正常行为，另外加固apk会关闭oat不会生成优化dex文件，请自行使用正确的classloader(非llpram.classloader)创建dexkit

**Comment by EatHatsuneShallots** [comment]
> 系统不会对apk进行改动

并不是这个意思，是指某些系统中的 `/system/app` 和 `/system/priv-app` 中的 apk 缺失 `classes.dex` 文件。例如 Android x86 - 4.0.x

**Comment by teble** [comment]
@EatHatsuneShallots 非正常系统行为的魔改，不予考虑，而且oat在不同安卓版本行为以及文件都是不一样的，所以完全没办法提供优化dex的解析支持

**Comment by teble** [comment]
@EatHatsuneShallots 如果你真想做，可以使用其它库将odex oat vdex等转换成dex文件后再进行解析，但是本库目前仅会解析.dex文件
