### ISSUE TITLE
Field usage in another class search

### ISSUE THREAD

**Issue by MichaelZhuravsky** [LuckyPray/DexKit#32]
Hello! 
Thx for great work! 
(and sorry for possible inaccuracy: I haven't found better place to ask questions)

I have two classes:
```
class Test1 {
  public static String a;
  public static String b;
  public static String c;
}
```
```
class Test2 {
  void foo() {
    if (Test1.b) { /*do smth*/ }
    // smth else
    Lod.d("TAG", "message")
  }
}
```

I can easy find Test2 class by a string ("message"). But is it possible to find what field of Test1 (in example: "b") is used in Test2 class (or in a specific method of Test2)?

**Comment by teble** [comment]
@MichaelZhuravsky Maybe you need MethodData.usingFields?

**Comment by MichaelZhuravsky** [comment]
@teble as I understand, MethodData.usingFields is a way to find a method, that used some field. I.e., to find Test2.foo by used Test1.b (or Test2.someField only?). 
But my task is the opposite: to find Test1.b itself

**Comment by teble** [comment]
@MichaelZhuravsky The return value of findMethod is MethodDataList, which contains a lot of metadata, including usingFields

**Comment by teble** [comment]
In your example:

```java
class Test2 {
  void foo() {
    if (Test1.b) { /*do smth*/ }
    // smth else
    Lod.d("TAG", "message");
  }
}
```

`foo()` uses `Test1.b`, so the value of `fooMethodData.usingFields` value is [FieldData@Test1.b]

**Comment by MichaelZhuravsky** [comment]
@teble, that is! Exactly what I want! Thx! :-)
