### ISSUE TITLE
无法打印 native 函数的调用以及被调用

### ISSUE THREAD

**Issue by xihan123** [LuckyPray/DexKit#6]
如题

**Comment by teble** [comment]
native函数实现是JNI负责的，这个dex层面无法处理，native函数被调用无法查找确实是一个bug

**Comment by xihan123** [comment]
但是用 xposed 钩住函数抛个异常可以打印调用栈 另类的查找调用和被调用喔

**Comment by teble** [comment]
> 但是用 xposed 钩住函数抛个异常可以打印调用栈 另类的查找调用和被调用喔

1.调用栈只针对异常点进行回溯，对于该函数调用的方法依旧是未知的
2.DexKit仅仅依赖于dex文件字节码的解析，在dex中native函数没有字节码存在（空数组），实现是由c层面负责的，so层面的信息不属于dex的范围，所以获取native函数的调用信息是不现实的

但是native函数的被调用关系是能处理的，需要点时间修改

**Comment by teble** [comment]
release 1.1.1 已发布，maven仓库由于缓存可能需要一点时间才能拉取依赖，如果是桌面平台测试记得先:main:clean再:main:run

**Comment by xihan123** [comment]
> > 但是用 xposed 钩住函数抛个异常可以打印调用栈 另类的查找调用和被调用喔
> 
> 1.调用栈只针对异常点进行回溯，对于该函数调用的方法依旧是未知的
> 2.DexKit仅仅依赖于dex文件字节码的解析，在dex中native函数没有字节码存在（空数组），实现是由c层面负责的，so层面的信息不属于dex的范围，所以获取native函数的调用信息是不现实的
> 
> 但是native函数的被调用关系是能处理的，需要点时间修改

还有一个问题，就是打印出来的调用顺序好像不太对劲，理论上来说应该是从上到下的打印顺序吧，我之前试了3次都是倒过来了

**Comment by teble** [comment]
不保证返回结果的有序性，因为会用set去重，依赖调用顺序作为特征没太必要

**Comment by teble** [comment]
如果非要顺序的话查询参数unique=false可以避免set去重以及乱序
